name: Build APK Fenix
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Obtener código
        uses: actions/checkout@v4

      - name: Instalar paquetes del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            python3-dev \
            python3-venv \
            openjdk-17-jdk \
            libsdl2-dev \
            libsdl2-image-dev \
            libsdl2-mixer-dev \
            libsdl2-ttf-dev \
            zlib1g-dev \
            libffi-dev \
            libssl-dev

      - name: Instalar Python y Buildozer
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install "cython<3.0.0"
          pip install buildozer

      - name: Mostrar archivos
        run: ls -la

      - name: Compilar APK
        run: |
          source .venv/bin/activate
          buildozer android debug 2>&1

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: FenixDecryptor-APK
          path: bin/*.apk
