name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK with Buildozer
      uses: Actions-R-Us/buildozer-action@v5
      with:
        command: buildozer android debug
        buildozer_version: master
