name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK with Buildozer
      uses: Actions-R-Us/buildozer-action@v5.1.0
      with:
        command: buildozer android debug
        buildozer_version: master

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: FenixAPK
        path: bin/*.apk
